### PR TITLE
Migrate doc into the astro website

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
Resolves https://github.com/Cap-go/capgo/issues/262
/claim #262 (https://github.com/Cap-go/capgo/issues/262)

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
@riderx This is ready to review.

**Comment by riderx** [comment]
@rishi-raj-jain i think we have a misunderstanding here, the doc was suppose to be into the website, not here ^^

**Comment by riderx** [comment]
That why the issue is in the website repo

**Comment by riderx** [comment]
Otherwise i really like the work you have made ! thanks the doc is superb !

**Comment by rishi-raj-jain** [comment]
@riderx 

1. No worries, by website do you mean the repo: https://github.com/Cap-go/website?

2. The issue though seems to be in the web app repo: https://github.com/Cap-go/capgo

> Otherwise i really like the work you have made ! thanks the doc is superb !

Thanks sir! Just confirm me the 1. and I'll complete that.

**Comment by rishi-raj-jain** [comment]
Also, have more of these? Would love to crush those.

**Comment by riderx** [comment]
Oh yes you are right it wasn’t clear.
Yea it should be in the website on path /docs

If you are good in designing you can work on the design of the org task I can split it in two parts

**Comment by rishi-raj-jain** [comment]
@riderx 

I just raised for this: https://github.com/Cap-go/website/pull/104

let me know if anything.

Which task are you referring to as the org task?

**Pull request closed without merging**
